import { db } from "./db";
import { categories } from "@shared/schema";
import { sql } from "drizzle-orm";

interface SeedCategory {
  name: string;
  nameAr: string;
  slug: string;
  description: string;
  descriptionAr: string;
  heroTitle: string;
  heroTitleAr: string;
  heroDescription: string;
  heroDescriptionAr: string;
  icon: string;
  level: number;
  displayOrder: number;
  parentSlug?: string; // For linking children to parents
  children?: SeedCategory[];
}

// Complete 3-level category hierarchy
const categoryTree: SeedCategory[] = [
  {
    name: "Software Services",
    nameAr: "خدمات البرمجيات",
    slug: "software-services",
    description: "Custom software development and IT solutions tailored to your business needs",
    descriptionAr: "تطوير برمجيات مخصصة وحلول تقنية مصممة خصيصاً لاحتياجات عملك",
    heroTitle: "Transform Your Business with Custom Software Solutions",
    heroTitleAr: "حوّل عملك بحلول برمجيات مخصصة",
    heroDescription: "Connect with expert software developers who can build scalable, innovative solutions for your unique business challenges",
    heroDescriptionAr: "تواصل مع مطوري برمجيات خبراء يمكنهم بناء حلول قابلة للتطوير ومبتكرة لتحديات عملك الفريدة",
    icon: "Code",
    level: 0,
    displayOrder: 1,
    children: [
      {
        name: "Web Development",
        nameAr: "تطوير المواقع الإلكترونية",
        slug: "web-development",
        description: "Professional website and web application development services",
        descriptionAr: "خدمات تطوير مواقع وتطبيقات ويب احترافية",
        heroTitle: "Build Powerful Web Solutions",
        heroTitleAr: "ابنِ حلول ويب قوية",
        heroDescription: "From simple websites to complex web applications, find developers who can bring your vision to life",
        heroDescriptionAr: "من المواقع البسيطة إلى تطبيقات الويب المعقدة، ابحث عن مطورين يمكنهم تحويل رؤيتك إلى واقع",
        icon: "Globe",
        level: 1,
        displayOrder: 1,
        children: [
          {
            name: "Frontend Development",
            nameAr: "تطوير الواجهات الأمامية",
            slug: "frontend-development",
            description: "React, Angular, Vue.js and modern frontend technologies",
            descriptionAr: "React و Angular و Vue.js وتقنيات الواجهات الأمامية الحديثة",
            heroTitle: "Create Beautiful User Interfaces",
            heroTitleAr: "أنشئ واجهات مستخدم جميلة",
            heroDescription: "Expert frontend developers specializing in modern frameworks and responsive design",
            heroDescriptionAr: "مطورو واجهات أمامية خبراء متخصصون في الأطر الحديثة والتصميم المتجاوب",
            icon: "Layout",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Backend Development",
            nameAr: "تطوير الخوادم الخلفية",
            slug: "backend-development",
            description: "Node.js, Python, PHP, Java server-side development",
            descriptionAr: "تطوير جانب الخادم بـ Node.js و Python و PHP و Java",
            heroTitle: "Build Robust Backend Systems",
            heroTitleAr: "ابنِ أنظمة خادم قوية",
            heroDescription: "Scalable APIs, databases, and server infrastructure",
            heroDescriptionAr: "واجهات برمجية وقواعد بيانات وبنية تحتية قابلة للتطوير",
            icon: "Server",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Full-Stack Development",
            nameAr: "التطوير الشامل",
            slug: "full-stack-development",
            description: "End-to-end web application development",
            descriptionAr: "تطوير تطبيقات ويب شاملة من البداية للنهاية",
            heroTitle: "Complete Web Solutions",
            heroTitleAr: "حلول ويب كاملة",
            heroDescription: "Full-stack developers who handle both frontend and backend",
            heroDescriptionAr: "مطورون شاملون يتعاملون مع الواجهة الأمامية والخلفية",
            icon: "Layers",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "E-commerce Platforms",
            nameAr: "منصات التجارة الإلكترونية",
            slug: "ecommerce-platforms",
            description: "Online store development with Shopify, WooCommerce, Magento",
            descriptionAr: "تطوير متاجر إلكترونية باستخدام Shopify و WooCommerce و Magento",
            heroTitle: "Launch Your Online Store",
            heroTitleAr: "أطلق متجرك الإلكتروني",
            heroDescription: "Build feature-rich e-commerce platforms that drive sales",
            heroDescriptionAr: "ابنِ منصات تجارة إلكترونية غنية بالميزات تزيد المبيعات",
            icon: "ShoppingCart",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
      {
        name: "Mobile Apps",
        nameAr: "تطبيقات الجوال",
        slug: "mobile-apps",
        description: "iOS and Android mobile application development",
        descriptionAr: "تطوير تطبيقات جوال لأنظمة iOS و Android",
        heroTitle: "Mobile Apps for Modern Businesses",
        heroTitleAr: "تطبيقات جوال للأعمال الحديثة",
        heroDescription: "Native and cross-platform mobile solutions",
        heroDescriptionAr: "حلول جوال أصلية ومتعددة المنصات",
        icon: "Smartphone",
        level: 1,
        displayOrder: 2,
        children: [
          {
            name: "iOS Development",
            nameAr: "تطوير iOS",
            slug: "ios-development",
            description: "Native iPhone and iPad app development with Swift",
            descriptionAr: "تطوير تطبيقات iPhone و iPad الأصلية باستخدام Swift",
            heroTitle: "Build Native iOS Apps",
            heroTitleAr: "ابنِ تطبيقات iOS أصلية",
            heroDescription: "Expert iOS developers for App Store success",
            heroDescriptionAr: "مطورو iOS خبراء لنجاح تطبيقك في App Store",
            icon: "Apple",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Android Development",
            nameAr: "تطوير Android",
            slug: "android-development",
            description: "Native Android app development with Kotlin and Java",
            descriptionAr: "تطوير تطبيقات Android أصلية باستخدام Kotlin و Java",
            heroTitle: "Create Powerful Android Apps",
            heroTitleAr: "أنشئ تطبيقات Android قوية",
            heroDescription: "Build apps that reach billions of Android users",
            heroDescriptionAr: "ابنِ تطبيقات تصل إلى مليارات مستخدمي Android",
            icon: "Smartphone",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Cross-Platform Development",
            nameAr: "التطوير متعدد المنصات",
            slug: "cross-platform-development",
            description: "React Native, Flutter, and Xamarin development",
            descriptionAr: "تطوير باستخدام React Native و Flutter و Xamarin",
            heroTitle: "One Codebase, Multiple Platforms",
            heroTitleAr: "كود واحد، منصات متعددة",
            heroDescription: "Cost-effective mobile apps for iOS and Android",
            heroDescriptionAr: "تطبيقات جوال فعالة من حيث التكلفة لـ iOS و Android",
            icon: "Layers",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Mobile UI/UX Design",
            nameAr: "تصميم واجهات تطبيقات الجوال",
            slug: "mobile-ui-ux-design",
            description: "User-friendly mobile app design and prototyping",
            descriptionAr: "تصميم تطبيقات جوال سهلة الاستخدام وإنشاء نماذج أولية",
            heroTitle: "Design Apps Users Love",
            heroTitleAr: "صمم تطبيقات يحبها المستخدمون",
            heroDescription: "Beautiful, intuitive mobile experiences",
            heroDescriptionAr: "تجارب جوال جميلة وبديهية",
            icon: "Palette",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
      {
        name: "Cloud Solutions",
        nameAr: "الحلول السحابية",
        slug: "cloud-solutions",
        description: "Cloud infrastructure, migration, and management services",
        descriptionAr: "خدمات البنية التحتية السحابية والترحيل والإدارة",
        heroTitle: "Scale Your Business with Cloud",
        heroTitleAr: "وسّع نطاق عملك بالسحابة",
        heroDescription: "AWS, Azure, Google Cloud experts for your digital transformation",
        heroDescriptionAr: "خبراء AWS و Azure و Google Cloud للتحول الرقمي",
        icon: "Cloud",
        level: 1,
        displayOrder: 3,
        children: [
          {
            name: "AWS Services",
            nameAr: "خدمات AWS",
            slug: "aws-services",
            description: "Amazon Web Services consulting and implementation",
            descriptionAr: "استشارات وتنفيذ خدمات Amazon Web Services",
            heroTitle: "Harness the Power of AWS",
            heroTitleAr: "استفد من قوة AWS",
            heroDescription: "EC2, S3, Lambda, and complete AWS solutions",
            heroDescriptionAr: "حلول AWS كاملة مع EC2 و S3 و Lambda",
            icon: "Cloud",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Azure Services",
            nameAr: "خدمات Azure",
            slug: "azure-services",
            description: "Microsoft Azure cloud solutions and integration",
            descriptionAr: "حلول وتكامل السحابة من Microsoft Azure",
            heroTitle: "Enterprise Cloud with Azure",
            heroTitleAr: "سحابة المؤسسات مع Azure",
            heroDescription: "Reliable Microsoft cloud infrastructure",
            heroDescriptionAr: "بنية تحتية سحابية موثوقة من Microsoft",
            icon: "Cloud",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Cloud Migration",
            nameAr: "الترحيل السحابي",
            slug: "cloud-migration",
            description: "Seamless migration from on-premise to cloud",
            descriptionAr: "ترحيل سلس من البنية التحتية المحلية إلى السحابة",
            heroTitle: "Move to Cloud Safely",
            heroTitleAr: "انتقل إلى السحابة بأمان",
            heroDescription: "Expert guidance for smooth cloud transitions",
            heroDescriptionAr: "إرشادات خبراء للانتقال السلس إلى السحابة",
            icon: "Upload",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "DevOps & CI/CD",
            nameAr: "DevOps والتكامل المستمر",
            slug: "devops-cicd",
            description: "Automated deployment pipelines and infrastructure as code",
            descriptionAr: "خطوط نشر آلية والبنية التحتية كرمز",
            heroTitle: "Automate Your Deployments",
            heroTitleAr: "أتمتة عمليات النشر",
            heroDescription: "Faster releases with continuous integration and delivery",
            heroDescriptionAr: "إصدارات أسرع مع التكامل والتسليم المستمر",
            icon: "GitBranch",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
      {
        name: "Data Analytics",
        nameAr: "تحليل البيانات",
        slug: "data-analytics",
        description: "Business intelligence, data science, and analytics solutions",
        descriptionAr: "ذكاء الأعمال وعلوم البيانات وحلول التحليلات",
        heroTitle: "Turn Data into Insights",
        heroTitleAr: "حوّل البيانات إلى رؤى",
        heroDescription: "Make data-driven decisions with expert analytics",
        heroDescriptionAr: "اتخذ قرارات مبنية على البيانات مع تحليلات الخبراء",
        icon: "BarChart3",
        level: 1,
        displayOrder: 4,
        children: [
          {
            name: "Business Intelligence",
            nameAr: "ذكاء الأعمال",
            slug: "business-intelligence",
            description: "Power BI, Tableau, and data visualization",
            descriptionAr: "Power BI و Tableau وتصور البيانات",
            heroTitle: "Visualize Your Success",
            heroTitleAr: "تصور نجاحك",
            heroDescription: "Interactive dashboards and business reports",
            heroDescriptionAr: "لوحات معلومات تفاعلية وتقارير أعمال",
            icon: "LineChart",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Machine Learning",
            nameAr: "التعلم الآلي",
            slug: "machine-learning",
            description: "AI and ML model development and deployment",
            descriptionAr: "تطوير ونشر نماذج الذكاء الاصطناعي والتعلم الآلي",
            heroTitle: "Intelligent Automation",
            heroTitleAr: "الأتمتة الذكية",
            heroDescription: "Predictive analytics and AI-powered solutions",
            heroDescriptionAr: "التحليلات التنبؤية والحلول المدعومة بالذكاء الاصطناعي",
            icon: "Brain",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Data Engineering",
            nameAr: "هندسة البيانات",
            slug: "data-engineering",
            description: "Data pipelines, ETL, and data warehouse solutions",
            descriptionAr: "خطوط البيانات و ETL وحلول مستودعات البيانات",
            heroTitle: "Build Robust Data Infrastructure",
            heroTitleAr: "ابنِ بنية تحتية قوية للبيانات",
            heroDescription: "Scalable data processing and storage systems",
            heroDescriptionAr: "أنظمة معالجة وتخزين بيانات قابلة للتطوير",
            icon: "Database",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Big Data Solutions",
            nameAr: "حلول البيانات الضخمة",
            slug: "big-data-solutions",
            description: "Hadoop, Spark, and distributed data processing",
            descriptionAr: "Hadoop و Spark ومعالجة البيانات الموزعة",
            heroTitle: "Process Data at Scale",
            heroTitleAr: "عالج البيانات على نطاق واسع",
            heroDescription: "Handle massive datasets efficiently",
            heroDescriptionAr: "تعامل مع مجموعات بيانات ضخمة بكفاءة",
            icon: "HardDrive",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
    ],
  },
  {
    name: "Digital Marketing Services",
    nameAr: "خدمات التسويق الرقمي",
    slug: "digital-marketing",
    description: "Comprehensive digital marketing strategies to grow your online presence",
    descriptionAr: "استراتيجيات تسويق رقمي شاملة لتنمية حضورك على الإنترنت",
    heroTitle: "Grow Your Business Online",
    heroTitleAr: "نمِّ عملك على الإنترنت",
    heroDescription: "Connect with marketing experts who drive results through data-driven strategies",
    heroDescriptionAr: "تواصل مع خبراء تسويق يحققون النتائج من خلال استراتيجيات مبنية على البيانات",
    icon: "Megaphone",
    level: 0,
    displayOrder: 2,
    children: [
      {
        name: "SEO Services",
        nameAr: "خدمات تحسين محركات البحث",
        slug: "seo-services",
        description: "Search engine optimization to improve your website ranking",
        descriptionAr: "تحسين محركات البحث لتحسين ترتيب موقعك",
        heroTitle: "Rank Higher on Google",
        heroTitleAr: "احصل على ترتيب أعلى في Google",
        heroDescription: "Organic traffic growth through proven SEO strategies",
        heroDescriptionAr: "نمو حركة المرور العضوية من خلال استراتيجيات SEO مجربة",
        icon: "Search",
        level: 1,
        displayOrder: 1,
        children: [
          {
            name: "On-Page SEO",
            nameAr: "تحسين محركات البحث الداخلي",
            slug: "on-page-seo",
            description: "Content optimization, meta tags, and site structure",
            descriptionAr: "تحسين المحتوى والوسوم والبنية الموقع",
            heroTitle: "Optimize Your Content",
            heroTitleAr: "حسّن محتواك",
            heroDescription: "Better rankings through optimized on-page elements",
            heroDescriptionAr: "تصنيفات أفضل من خلال عناصر داخلية محسّنة",
            icon: "FileText",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Off-Page SEO",
            nameAr: "تحسين محركات البحث الخارجي",
            slug: "off-page-seo",
            description: "Link building, brand mentions, and authority building",
            descriptionAr: "بناء الروابط والإشارات للعلامة التجارية وبناء السلطة",
            heroTitle: "Build Your Authority",
            heroTitleAr: "ابنِ سلطتك",
            heroDescription: "Quality backlinks for domain authority",
            heroDescriptionAr: "روابط خلفية عالية الجودة لسلطة المجال",
            icon: "Link",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Technical SEO",
            nameAr: "تحسين محركات البحث التقني",
            slug: "technical-seo",
            description: "Site speed, mobile optimization, and crawlability",
            descriptionAr: "سرعة الموقع والتحسين للجوال وقابلية الزحف",
            heroTitle: "Technical Excellence",
            heroTitleAr: "التميز التقني",
            heroDescription: "Fast, crawlable websites that rank better",
            heroDescriptionAr: "مواقع سريعة وقابلة للزحف تحصل على ترتيب أفضل",
            icon: "Settings",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Local SEO",
            nameAr: "تحسين محركات البحث المحلي",
            slug: "local-seo",
            description: "Google My Business and local search optimization",
            descriptionAr: "تحسين Google My Business والبحث المحلي",
            heroTitle: "Dominate Local Search",
            heroTitleAr: "هيمن على البحث المحلي",
            heroDescription: "Get found by customers in your area",
            heroDescriptionAr: "اجعل العملاء في منطقتك يجدونك",
            icon: "MapPin",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
      {
        name: "Social Media",
        nameAr: "وسائل التواصل الاجتماعي",
        slug: "social-media",
        description: "Social media strategy, management, and advertising",
        descriptionAr: "استراتيجية وإدارة وإعلانات وسائل التواصل الاجتماعي",
        heroTitle: "Engage Your Audience",
        heroTitleAr: "تفاعل مع جمهورك",
        heroDescription: "Build communities and drive engagement across social platforms",
        heroDescriptionAr: "ابنِ مجتمعات وزد التفاعل عبر منصات التواصل الاجتماعي",
        icon: "Share2",
        level: 1,
        displayOrder: 2,
        children: [
          {
            name: "Facebook Marketing",
            nameAr: "التسويق عبر Facebook",
            slug: "facebook-marketing",
            description: "Facebook ads, page management, and community building",
            descriptionAr: "إعلانات Facebook وإدارة الصفحات وبناء المجتمعات",
            heroTitle: "Reach Billions on Facebook",
            heroTitleAr: "اوصل لمليارات على Facebook",
            heroDescription: "Targeted ads and organic growth strategies",
            heroDescriptionAr: "إعلانات مستهدفة واستراتيجيات نمو عضوي",
            icon: "Facebook",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Instagram Marketing",
            nameAr: "التسويق عبر Instagram",
            slug: "instagram-marketing",
            description: "Instagram content, stories, reels, and influencer partnerships",
            descriptionAr: "محتوى Instagram والقصص والريلز وشراكات المؤثرين",
            heroTitle: "Visual Storytelling",
            heroTitleAr: "سرد القصص المرئي",
            heroDescription: "Engage audiences through stunning visuals",
            heroDescriptionAr: "تفاعل مع الجماهير من خلال صور مذهلة",
            icon: "Instagram",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "LinkedIn Marketing",
            nameAr: "التسويق عبر LinkedIn",
            slug: "linkedin-marketing",
            description: "B2B marketing, thought leadership, and professional networking",
            descriptionAr: "التسويق B2B والقيادة الفكرية والشبكات المهنية",
            heroTitle: "Professional Networking",
            heroTitleAr: "الشبكات المهنية",
            heroDescription: "Reach decision-makers and industry professionals",
            heroDescriptionAr: "اوصل لصانعي القرار والمحترفين في المجال",
            icon: "Linkedin",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Twitter/X Marketing",
            nameAr: "التسويق عبر Twitter/X",
            slug: "twitter-marketing",
            description: "Real-time engagement and brand conversations",
            descriptionAr: "التفاعل الفوري ومحادثات العلامة التجارية",
            heroTitle: "Join the Conversation",
            heroTitleAr: "انضم للمحادثة",
            heroDescription: "Build brand awareness through trending topics",
            heroDescriptionAr: "ابنِ الوعي بالعلامة التجارية من خلال المواضيع الرائجة",
            icon: "Twitter",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
      {
        name: "Content Marketing",
        nameAr: "تسويق المحتوى",
        slug: "content-marketing",
        description: "Strategic content creation to attract and engage your audience",
        descriptionAr: "إنشاء محتوى استراتيجي لجذب وإشراك جمهورك",
        heroTitle: "Content That Converts",
        heroTitleAr: "محتوى يحقق التحويل",
        heroDescription: "Compelling content that drives business results",
        heroDescriptionAr: "محتوى مقنع يحقق نتائج أعمال",
        icon: "PenTool",
        level: 1,
        displayOrder: 3,
        children: [
          {
            name: "Blog Writing",
            nameAr: "كتابة المدونات",
            slug: "blog-writing",
            description: "SEO-optimized blog posts and articles",
            descriptionAr: "مقالات ومنشورات مدونة محسنة لمحركات البحث",
            heroTitle: "Publish Engaging Content",
            heroTitleAr: "انشر محتوى جذاب",
            heroDescription: "Regular, high-quality blog content",
            heroDescriptionAr: "محتوى مدونة عالي الجودة ومنتظم",
            icon: "BookOpen",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Video Production",
            nameAr: "إنتاج الفيديو",
            slug: "video-production",
            description: "Professional video content for marketing and engagement",
            descriptionAr: "محتوى فيديو احترافي للتسويق والتفاعل",
            heroTitle: "Captivate with Video",
            heroTitleAr: "اجذب الانتباه بالفيديو",
            heroDescription: "Engaging video content that tells your story",
            heroDescriptionAr: "محتوى فيديو جذاب يروي قصتك",
            icon: "Video",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Copywriting",
            nameAr: "كتابة النصوص الإعلانية",
            slug: "copywriting",
            description: "Persuasive copy for websites, ads, and sales materials",
            descriptionAr: "نصوص مقنعة للمواقع والإعلانات ومواد المبيعات",
            heroTitle: "Words That Sell",
            heroTitleAr: "كلمات تبيع",
            heroDescription: "Compelling copy that drives action",
            heroDescriptionAr: "نصوص مقنعة تدفع للعمل",
            icon: "Feather",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Infographics & Design",
            nameAr: "الإنفوجرافيك والتصميم",
            slug: "infographics-design",
            description: "Visual content design and data visualization",
            descriptionAr: "تصميم المحتوى المرئي وتصور البيانات",
            heroTitle: "Visualize Your Message",
            heroTitleAr: "صور رسالتك",
            heroDescription: "Eye-catching designs that simplify complex ideas",
            heroDescriptionAr: "تصاميم لافتة للنظر تبسط الأفكار المعقدة",
            icon: "Image",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
      {
        name: "Email Marketing",
        nameAr: "التسويق عبر البريد الإلكتروني",
        slug: "email-marketing",
        description: "Email campaigns, automation, and list management",
        descriptionAr: "حملات البريد الإلكتروني والأتمتة وإدارة القوائم",
        heroTitle: "Direct Communication",
        heroTitleAr: "التواصل المباشر",
        heroDescription: "Personalized email campaigns that drive conversions",
        heroDescriptionAr: "حملات بريد إلكتروني مخصصة تحقق التحويلات",
        icon: "Mail",
        level: 1,
        displayOrder: 4,
        children: [
          {
            name: "Newsletter Campaigns",
            nameAr: "حملات النشرات الإخبارية",
            slug: "newsletter-campaigns",
            description: "Regular newsletters to keep customers engaged",
            descriptionAr: "نشرات إخبارية منتظمة لإبقاء العملاء متفاعلين",
            heroTitle: "Stay Connected",
            heroTitleAr: "ابقَ متصلاً",
            heroDescription: "Build relationships through valuable newsletters",
            heroDescriptionAr: "ابنِ علاقات من خلال نشرات إخبارية قيّمة",
            icon: "Newspaper",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Marketing Automation",
            nameAr: "أتمتة التسويق",
            slug: "marketing-automation",
            description: "Automated email sequences and drip campaigns",
            descriptionAr: "تسلسلات بريد إلكتروني آلية وحملات متدرجة",
            heroTitle: "Automate Your Growth",
            heroTitleAr: "أتمت نموك",
            heroDescription: "Smart automation that nurtures leads",
            heroDescriptionAr: "أتمتة ذكية ترعى العملاء المحتملين",
            icon: "Zap",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "List Management",
            nameAr: "إدارة القوائم",
            slug: "list-management",
            description: "Email list building, segmentation, and maintenance",
            descriptionAr: "بناء قوائم البريد الإلكتروني وتقسيمها وصيانتها",
            heroTitle: "Grow Your Audience",
            heroTitleAr: "نمِّ جمهورك",
            heroDescription: "Build and maintain high-quality email lists",
            heroDescriptionAr: "ابنِ وحافظ على قوائم بريد إلكتروني عالية الجودة",
            icon: "Users",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Email Design",
            nameAr: "تصميم البريد الإلكتروني",
            slug: "email-design",
            description: "Responsive email templates and visual design",
            descriptionAr: "قوالب بريد إلكتروني متجاوبة وتصميم مرئي",
            heroTitle: "Beautiful Emails",
            heroTitleAr: "رسائل جميلة",
            heroDescription: "Professionally designed emails that get opened",
            heroDescriptionAr: "رسائل بريد إلكتروني مصممة باحترافية تُفتح",
            icon: "Layout",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
    ],
  },
  {
    name: "Human Resources",
    nameAr: "الموارد البشرية",
    slug: "human-resources",
    description: "HR solutions for talent acquisition, development, and management",
    descriptionAr: "حلول الموارد البشرية لاكتساب المواهب وتطويرها وإدارتها",
    heroTitle: "Empower Your Workforce",
    heroTitleAr: "مكّن قوتك العاملة",
    heroDescription: "Find HR experts who help you build and nurture great teams",
    heroDescriptionAr: "ابحث عن خبراء الموارد البشرية الذين يساعدونك في بناء ورعاية فرق رائعة",
    icon: "Users",
    level: 0,
    displayOrder: 3,
    children: [
      {
        name: "Recruitment",
        nameAr: "التوظيف",
        slug: "recruitment",
        description: "End-to-end talent acquisition and hiring services",
        descriptionAr: "خدمات اكتساب المواهب والتوظيف الشاملة",
        heroTitle: "Find Top Talent",
        heroTitleAr: "اعثر على أفضل المواهب",
        heroDescription: "Attract, screen, and hire the best candidates",
        heroDescriptionAr: "اجذب وفحص ووظف أفضل المرشحين",
        icon: "UserPlus",
        level: 1,
        displayOrder: 1,
        children: [
          {
            name: "Executive Search",
            nameAr: "البحث التنفيذي",
            slug: "executive-search",
            description: "Senior leadership and C-level recruitment",
            descriptionAr: "توظيف القيادة العليا والمستوى التنفيذي",
            heroTitle: "Leadership Recruitment",
            heroTitleAr: "توظيف القيادات",
            heroDescription: "Find exceptional leaders for your organization",
            heroDescriptionAr: "اعثر على قادة استثنائيين لمؤسستك",
            icon: "Award",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Technical Hiring",
            nameAr: "التوظيف التقني",
            slug: "technical-hiring",
            description: "IT and engineering talent acquisition",
            descriptionAr: "اكتساب مواهب تقنية المعلومات والهندسة",
            heroTitle: "Hire Tech Talent",
            heroTitleAr: "وظف مواهب تقنية",
            heroDescription: "Specialized recruitment for technical roles",
            heroDescriptionAr: "توظيف متخصص للأدوار التقنية",
            icon: "Code",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Volume Hiring",
            nameAr: "التوظيف بالجملة",
            slug: "volume-hiring",
            description: "Mass recruitment and campus hiring programs",
            descriptionAr: "التوظيف الجماعي وبرامج التوظيف من الحرم الجامعي",
            heroTitle: "Scale Your Team Fast",
            heroTitleAr: "وسّع فريقك بسرعة",
            heroDescription: "Efficient bulk hiring solutions",
            heroDescriptionAr: "حلول توظيف جماعي فعالة",
            icon: "Users",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Applicant Tracking",
            nameAr: "تتبع المتقدمين",
            slug: "applicant-tracking",
            description: "ATS implementation and recruitment workflow optimization",
            descriptionAr: "تنفيذ نظام تتبع المتقدمين وتحسين سير عمل التوظيف",
            heroTitle: "Streamline Hiring",
            heroTitleAr: "بسّط عملية التوظيف",
            heroDescription: "Organize and track candidates efficiently",
            heroDescriptionAr: "نظّم وتتبع المرشحين بكفاءة",
            icon: "Filter",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
      {
        name: "Training & Development",
        nameAr: "التدريب والتطوير",
        slug: "training-development",
        description: "Employee learning, skill development, and career growth programs",
        descriptionAr: "برامج تعلم الموظفين وتطوير المهارات والنمو الوظيفي",
        heroTitle: "Develop Your People",
        heroTitleAr: "طور موظفيك",
        heroDescription: "Build skills and capabilities for business success",
        heroDescriptionAr: "ابنِ المهارات والقدرات لنجاح الأعمال",
        icon: "GraduationCap",
        level: 1,
        displayOrder: 2,
        children: [
          {
            name: "Leadership Training",
            nameAr: "تدريب القيادة",
            slug: "leadership-training",
            description: "Management and leadership development programs",
            descriptionAr: "برامج تطوير الإدارة والقيادة",
            heroTitle: "Build Future Leaders",
            heroTitleAr: "ابنِ قادة المستقبل",
            heroDescription: "Cultivate leadership skills at all levels",
            heroDescriptionAr: "اغرس مهارات القيادة على جميع المستويات",
            icon: "Target",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Technical Training",
            nameAr: "التدريب التقني",
            slug: "technical-training",
            description: "IT, software, and technical skills training",
            descriptionAr: "تدريب على تقنية المعلومات والبرمجيات والمهارات التقنية",
            heroTitle: "Technical Excellence",
            heroTitleAr: "التميز التقني",
            heroDescription: "Keep your team's technical skills current",
            heroDescriptionAr: "حافظ على مهارات فريقك التقنية محدثة",
            icon: "Cpu",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Soft Skills Training",
            nameAr: "تدريب المهارات الناعمة",
            slug: "soft-skills-training",
            description: "Communication, teamwork, and interpersonal skills",
            descriptionAr: "التواصل والعمل الجماعي والمهارات الشخصية",
            heroTitle: "People Skills Matter",
            heroTitleAr: "المهارات الشخصية مهمة",
            heroDescription: "Enhance collaboration and communication",
            heroDescriptionAr: "عزز التعاون والتواصل",
            icon: "MessageCircle",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "E-Learning Platforms",
            nameAr: "منصات التعلم الإلكتروني",
            slug: "elearning-platforms",
            description: "Online training systems and learning management",
            descriptionAr: "أنظمة التدريب عبر الإنترنت وإدارة التعلم",
            heroTitle: "Digital Learning",
            heroTitleAr: "التعلم الرقمي",
            heroDescription: "Scalable online training solutions",
            heroDescriptionAr: "حلول تدريب عبر الإنترنت قابلة للتطوير",
            icon: "Monitor",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
      {
        name: "Payroll Services",
        nameAr: "خدمات كشوف المرتبات",
        slug: "payroll-services",
        description: "Comprehensive payroll processing and compliance management",
        descriptionAr: "معالجة شاملة لكشوف المرتبات وإدارة الامتثال",
        heroTitle: "Streamline Payroll",
        heroTitleAr: "بسّط كشوف المرتبات",
        heroDescription: "Accurate, timely payroll every time",
        heroDescriptionAr: "كشوف مرتبات دقيقة وفي الوقت المحدد دائماً",
        icon: "DollarSign",
        level: 1,
        displayOrder: 3,
        children: [
          {
            name: "Payroll Processing",
            nameAr: "معالجة كشوف المرتبات",
            slug: "payroll-processing",
            description: "Monthly salary calculation and disbursement",
            descriptionAr: "حساب الرواتب الشهرية وصرفها",
            heroTitle: "Accurate Payroll",
            heroTitleAr: "كشوف مرتبات دقيقة",
            heroDescription: "Error-free salary processing",
            heroDescriptionAr: "معالجة رواتب خالية من الأخطاء",
            icon: "Calculator",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Tax Compliance",
            nameAr: "الامتثال الضريبي",
            slug: "tax-compliance",
            description: "Income tax, VAT, and payroll tax management",
            descriptionAr: "إدارة ضريبة الدخل وضريبة القيمة المضافة وضرائب الرواتب",
            heroTitle: "Stay Compliant",
            heroTitleAr: "ابقَ ملتزماً",
            heroDescription: "Navigate tax regulations confidently",
            heroDescriptionAr: "تنقل في اللوائح الضريبية بثقة",
            icon: "FileCheck",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Benefits Administration",
            nameAr: "إدارة المزايا",
            slug: "benefits-administration",
            description: "Employee benefits, insurance, and pension management",
            descriptionAr: "إدارة مزايا الموظفين والتأمين والمعاشات",
            heroTitle: "Manage Benefits",
            heroTitleAr: "إدارة المزايا",
            heroDescription: "Comprehensive benefits administration",
            heroDescriptionAr: "إدارة شاملة للمزايا",
            icon: "Heart",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Payroll Software",
            nameAr: "برامج كشوف المرتبات",
            slug: "payroll-software",
            description: "Automated payroll systems and HRMS integration",
            descriptionAr: "أنظمة كشوف مرتبات آلية وتكامل مع أنظمة إدارة الموارد البشرية",
            heroTitle: "Automate Payroll",
            heroTitleAr: "أتمت كشوف المرتبات",
            heroDescription: "Modern payroll technology solutions",
            heroDescriptionAr: "حلول تكنولوجيا كشوف المرتبات الحديثة",
            icon: "Laptop",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
      {
        name: "HR Consulting",
        nameAr: "استشارات الموارد البشرية",
        slug: "hr-consulting",
        description: "Strategic HR advisory and organizational development",
        descriptionAr: "استشارات الموارد البشرية الاستراتيجية والتطوير التنظيمي",
        heroTitle: "Strategic HR Guidance",
        heroTitleAr: "إرشادات موارد بشرية استراتيجية",
        heroDescription: "Expert advice for HR transformation",
        heroDescriptionAr: "نصائح خبراء للتحول في الموارد البشرية",
        icon: "Briefcase",
        level: 1,
        displayOrder: 4,
        children: [
          {
            name: "HR Strategy",
            nameAr: "استراتيجية الموارد البشرية",
            slug: "hr-strategy",
            description: "Workforce planning and HR roadmap development",
            descriptionAr: "تخطيط القوى العاملة وتطوير خارطة طريق الموارد البشرية",
            heroTitle: "Plan Your HR Future",
            heroTitleAr: "خطط لمستقبل مواردك البشرية",
            heroDescription: "Align HR with business objectives",
            heroDescriptionAr: "وافق الموارد البشرية مع أهداف العمل",
            icon: "TrendingUp",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Organizational Design",
            nameAr: "التصميم التنظيمي",
            slug: "organizational-design",
            description: "Structure, roles, and reporting relationships optimization",
            descriptionAr: "تحسين الهيكل والأدوار وعلاقات الإبلاغ",
            heroTitle: "Optimize Your Structure",
            heroTitleAr: "حسّن هيكلك",
            heroDescription: "Design organizations for efficiency",
            heroDescriptionAr: "صمم منظمات من أجل الكفاءة",
            icon: "Network",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Change Management",
            nameAr: "إدارة التغيير",
            slug: "change-management",
            description: "Organizational transformation and change initiatives",
            descriptionAr: "التحول التنظيمي ومبادرات التغيير",
            heroTitle: "Navigate Change",
            heroTitleAr: "تنقل في التغيير",
            heroDescription: "Guide your organization through transitions",
            heroDescriptionAr: "وجه مؤسستك عبر المراحل الانتقالية",
            icon: "Repeat",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Performance Management",
            nameAr: "إدارة الأداء",
            slug: "performance-management",
            description: "KPIs, performance reviews, and talent assessment",
            descriptionAr: "مؤشرات الأداء الرئيسية ومراجعات الأداء وتقييم المواهب",
            heroTitle: "Drive Performance",
            heroTitleAr: "حفز الأداء",
            heroDescription: "Measure and improve employee performance",
            heroDescriptionAr: "قِس وحسّن أداء الموظفين",
            icon: "BarChart",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
    ],
  },
  {
    name: "Infra & Hardware Supplies",
    nameAr: "البنية التحتية ولوازم الأجهزة",
    slug: "infra-hardware",
    description: "IT infrastructure, networking, and hardware procurement services",
    descriptionAr: "البنية التحتية لتقنية المعلومات والشبكات وخدمات شراء الأجهزة",
    heroTitle: "Build Robust IT Infrastructure",
    heroTitleAr: "ابنِ بنية تحتية قوية لتقنية المعلومات",
    heroDescription: "Find experts to design, deploy, and maintain your IT infrastructure",
    heroDescriptionAr: "ابحث عن خبراء لتصميم ونشر وصيانة البنية التحتية لتقنية المعلومات",
    icon: "HardDrive",
    level: 0,
    displayOrder: 4,
    children: [
      {
        name: "Network Equipment",
        nameAr: "معدات الشبكات",
        slug: "network-equipment",
        description: "Routers, switches, firewalls, and network infrastructure",
        descriptionAr: "أجهزة التوجيه والمحولات وجدران الحماية والبنية التحتية للشبكات",
        heroTitle: "Connect Your Business",
        heroTitleAr: "اربط عملك",
        heroDescription: "Enterprise-grade networking solutions",
        heroDescriptionAr: "حلول شبكات على مستوى المؤسسات",
        icon: "Network",
        level: 1,
        displayOrder: 1,
        children: [
          {
            name: "Enterprise Routers",
            nameAr: "أجهزة التوجيه للمؤسسات",
            slug: "enterprise-routers",
            description: "High-performance routers for business networks",
            descriptionAr: "أجهزة توجيه عالية الأداء لشبكات الأعمال",
            heroTitle: "Reliable Connectivity",
            heroTitleAr: "اتصال موثوق",
            heroDescription: "Fast, secure network routing",
            heroDescriptionAr: "توجيه شبكة سريع وآمن",
            icon: "Router",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Network Switches",
            nameAr: "محولات الشبكة",
            slug: "network-switches",
            description: "Managed and unmanaged switches for all network sizes",
            descriptionAr: "محولات مُدارة وغير مُدارة لجميع أحجام الشبكات",
            heroTitle: "Efficient Switching",
            heroTitleAr: "تحويل فعال",
            heroDescription: "Optimize network traffic flow",
            heroDescriptionAr: "حسّن تدفق حركة مرور الشبكة",
            icon: "Server",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Firewalls & Security",
            nameAr: "جدران الحماية والأمان",
            slug: "firewalls-security",
            description: "Next-generation firewalls and network security appliances",
            descriptionAr: "جدران حماية الجيل التالي وأجهزة أمان الشبكات",
            heroTitle: "Protect Your Network",
            heroTitleAr: "احمِ شبكتك",
            heroDescription: "Advanced threat protection",
            heroDescriptionAr: "حماية متقدمة من التهديدات",
            icon: "Shield",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Wireless Access Points",
            nameAr: "نقاط الوصول اللاسلكية",
            slug: "wireless-access-points",
            description: "Wi-Fi 6 and enterprise wireless solutions",
            descriptionAr: "Wi-Fi 6 وحلول لاسلكية للمؤسسات",
            heroTitle: "Seamless Wireless",
            heroTitleAr: "لاسلكي سلس",
            heroDescription: "Fast, reliable Wi-Fi coverage",
            heroDescriptionAr: "تغطية Wi-Fi سريعة وموثوقة",
            icon: "Wifi",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
      {
        name: "Servers & Storage",
        nameAr: "الخوادم والتخزين",
        slug: "servers-storage",
        description: "Server hardware, storage systems, and data center equipment",
        descriptionAr: "أجهزة الخوادم وأنظمة التخزين ومعدات مراكز البيانات",
        heroTitle: "Power Your Data Center",
        heroTitleAr: "شغّل مركز بياناتك",
        heroDescription: "Scalable servers and storage solutions",
        heroDescriptionAr: "خوادم وحلول تخزين قابلة للتطوير",
        icon: "Database",
        level: 1,
        displayOrder: 2,
        children: [
          {
            name: "Rack Servers",
            nameAr: "خوادم Rack",
            slug: "rack-servers",
            description: "Rackmount servers for data centers",
            descriptionAr: "خوادم قابلة للتركيب في الرفوف لمراكز البيانات",
            heroTitle: "Datacenter Performance",
            heroTitleAr: "أداء مركز البيانات",
            heroDescription: "High-density computing power",
            heroDescriptionAr: "قوة حوسبة عالية الكثافة",
            icon: "Server",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Storage Arrays",
            nameAr: "مصفوفات التخزين",
            slug: "storage-arrays",
            description: "SAN, NAS, and enterprise storage systems",
            descriptionAr: "SAN و NAS وأنظمة تخزين المؤسسات",
            heroTitle: "Scalable Storage",
            heroTitleAr: "تخزين قابل للتطوير",
            heroDescription: "Reliable data storage solutions",
            heroDescriptionAr: "حلول تخزين بيانات موثوقة",
            icon: "HardDrive",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Backup Solutions",
            nameAr: "حلول النسخ الاحتياطي",
            slug: "backup-solutions",
            description: "Data backup, disaster recovery, and archiving",
            descriptionAr: "النسخ الاحتياطي للبيانات والتعافي من الكوارث والأرشفة",
            heroTitle: "Protect Your Data",
            heroTitleAr: "احمِ بياناتك",
            heroDescription: "Comprehensive backup and recovery",
            heroDescriptionAr: "نسخ احتياطي واستعادة شاملة",
            icon: "Archive",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Virtualization",
            nameAr: "المحاكاة الافتراضية",
            slug: "virtualization",
            description: "VMware, Hyper-V, and virtualization infrastructure",
            descriptionAr: "VMware و Hyper-V والبنية التحتية للمحاكاة الافتراضية",
            heroTitle: "Maximize Resources",
            heroTitleAr: "عظّم الموارد",
            heroDescription: "Efficient server virtualization",
            heroDescriptionAr: "محاكاة خوادم فعالة",
            icon: "Box",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
      {
        name: "Security Systems",
        nameAr: "أنظمة الأمان",
        slug: "security-systems",
        description: "Physical and digital security solutions",
        descriptionAr: "حلول الأمان المادية والرقمية",
        heroTitle: "Secure Your Assets",
        heroTitleAr: "أمّن أصولك",
        heroDescription: "Comprehensive security for your business",
        heroDescriptionAr: "أمان شامل لعملك",
        icon: "Lock",
        level: 1,
        displayOrder: 3,
        children: [
          {
            name: "CCTV Systems",
            nameAr: "أنظمة كاميرات المراقبة",
            slug: "cctv-systems",
            description: "IP cameras and video surveillance solutions",
            descriptionAr: "كاميرات IP وحلول مراقبة الفيديو",
            heroTitle: "Video Surveillance",
            heroTitleAr: "المراقبة بالفيديو",
            heroDescription: "Monitor your premises 24/7",
            heroDescriptionAr: "راقب مقرك على مدار الساعة",
            icon: "Camera",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Access Control",
            nameAr: "التحكم في الوصول",
            slug: "access-control",
            description: "Biometric and card-based access systems",
            descriptionAr: "أنظمة الوصول البيومترية والمستندة إلى البطاقات",
            heroTitle: "Control Entry Points",
            heroTitleAr: "تحكم في نقاط الدخول",
            heroDescription: "Secure physical access management",
            heroDescriptionAr: "إدارة وصول مادي آمنة",
            icon: "Fingerprint",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Cybersecurity Tools",
            nameAr: "أدوات الأمن السيبراني",
            slug: "cybersecurity-tools",
            description: "Endpoint protection, SIEM, and security software",
            descriptionAr: "حماية نقاط النهاية و SIEM وبرامج الأمان",
            heroTitle: "Digital Protection",
            heroTitleAr: "الحماية الرقمية",
            heroDescription: "Advanced cybersecurity solutions",
            heroDescriptionAr: "حلول أمن سيبراني متقدمة",
            icon: "ShieldCheck",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Alarm Systems",
            nameAr: "أنظمة الإنذار",
            slug: "alarm-systems",
            description: "Intrusion detection and alert systems",
            descriptionAr: "أنظمة كشف التسلل والتنبيه",
            heroTitle: "Instant Alerts",
            heroTitleAr: "تنبيهات فورية",
            heroDescription: "Real-time security notifications",
            heroDescriptionAr: "إشعارات أمنية فورية",
            icon: "Bell",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
      {
        name: "IT Peripherals",
        nameAr: "ملحقات تقنية المعلومات",
        slug: "it-peripherals",
        description: "Computers, monitors, printers, and office IT equipment",
        descriptionAr: "أجهزة الكمبيوتر والشاشات والطابعات ومعدات تقنية المعلومات المكتبية",
        heroTitle: "Complete Your IT Setup",
        heroTitleAr: "أكمل إعداد تقنية المعلومات",
        heroDescription: "All the equipment your office needs",
        heroDescriptionAr: "جميع المعدات التي يحتاجها مكتبك",
        icon: "Monitor",
        level: 1,
        displayOrder: 4,
        children: [
          {
            name: "Desktop Computers",
            nameAr: "أجهزة كمبيوتر مكتبية",
            slug: "desktop-computers",
            description: "Business desktops and workstations",
            descriptionAr: "أجهزة كمبيوتر مكتبية ومحطات عمل للأعمال",
            heroTitle: "Powerful Workstations",
            heroTitleAr: "محطات عمل قوية",
            heroDescription: "High-performance computers for your team",
            heroDescriptionAr: "أجهزة كمبيوتر عالية الأداء لفريقك",
            icon: "Pc",
            level: 2,
            displayOrder: 1,
          },
          {
            name: "Laptops & Notebooks",
            nameAr: "أجهزة اللابتوب والنوت بوك",
            slug: "laptops-notebooks",
            description: "Business laptops and mobile computing",
            descriptionAr: "أجهزة لابتوب الأعمال والحوسبة المتنقلة",
            heroTitle: "Mobile Productivity",
            heroTitleAr: "إنتاجية متنقلة",
            heroDescription: "Work from anywhere",
            heroDescriptionAr: "اعمل من أي مكان",
            icon: "Laptop",
            level: 2,
            displayOrder: 2,
          },
          {
            name: "Printers & Scanners",
            nameAr: "الطابعات والماسحات الضوئية",
            slug: "printers-scanners",
            description: "Office printers, MFPs, and document scanners",
            descriptionAr: "طابعات المكاتب والأجهزة متعددة الوظائف والماسحات الضوئية",
            heroTitle: "Document Management",
            heroTitleAr: "إدارة المستندات",
            heroDescription: "Efficient printing and scanning",
            heroDescriptionAr: "طباعة ومسح ضوئي فعالة",
            icon: "Printer",
            level: 2,
            displayOrder: 3,
          },
          {
            name: "Monitors & Displays",
            nameAr: "الشاشات والعرض",
            slug: "monitors-displays",
            description: "Professional monitors and display solutions",
            descriptionAr: "شاشات احترافية وحلول عرض",
            heroTitle: "Crystal Clear Displays",
            heroTitleAr: "شاشات واضحة تماماً",
            heroDescription: "High-quality monitors for productivity",
            heroDescriptionAr: "شاشات عالية الجودة للإنتاجية",
            icon: "Monitor",
            level: 2,
            displayOrder: 4,
          },
        ],
      },
    ],
  },
];

// Helper function to insert category and its children recursively
async function insertCategoryTree(
  category: SeedCategory,
  parentId: string | null = null,
  db: any
): Promise<string> {
  // Insert current category
  const [inserted] = await db
    .insert(categories)
    .values({
      name: category.name,
      nameAr: category.nameAr,
      slug: category.slug,
      description: category.description,
      descriptionAr: category.descriptionAr,
      heroTitle: category.heroTitle,
      heroTitleAr: category.heroTitleAr,
      heroDescription: category.heroDescription,
      heroDescriptionAr: category.heroDescriptionAr,
      icon: category.icon,
      level: category.level,
      displayOrder: category.displayOrder,
      parentId: parentId,
      active: true,
      visible: true,
      featured: category.level === 0, // Feature root categories
    })
    .returning({ id: categories.id });

  const categoryId = inserted.id;

  // Insert children if any
  if (category.children && category.children.length > 0) {
    for (const child of category.children) {
      await insertCategoryTree(child, categoryId, db);
    }
  }

  return categoryId;
}

// Main seed function
export async function seedCategories() {
  console.log("Starting category seeding...");
  
  try {
    // Delete existing categories (CASCADE will handle children)
    await db.delete(categories);
    console.log("Cleared existing categories");

    // Insert all category trees
    for (const rootCategory of categoryTree) {
      await insertCategoryTree(rootCategory, null, db);
      console.log(`Inserted category tree: ${rootCategory.name}`);
    }

    console.log("✅ Category seeding completed successfully!");
    console.log("Total categories created:");
    console.log("- 4 primary categories (level 0)");
    console.log("- 16 subcategories (level 1)");
    console.log("- 64 super-subcategories (level 2)");
    console.log("Total: 84 categories");
  } catch (error) {
    console.error("❌ Error seeding categories:", error);
    throw error;
  }
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedCategories()
    .then(() => {
      console.log("Seed complete!");
      process.exit(0);
    })
    .catch((error) => {
      console.error("Seed failed:", error);
      process.exit(1);
    });
}
